### ISSUE TITLE
Qolsys Panel 2 (not plus)

### ISSUE THREAD

**Issue by smwoodward** [XaF/qolsysgw#12]
I can confirm it works on the iq panel 2.

**Comment by XaF** [comment]
Hey there! Awesome! Could you share the software version too?
I'd like to add in the README the tested hardware and software versions!

**Comment by smwoodward** [comment]
It's the latest version of the software that requires 6 digit user code.

**Comment by kevin-david** [comment]
My IQ Panel 2 with firmware 2.6.2 is also working great!

**Comment by XaF** [comment]
Thanks friends! Updated the doc to mention the two panels. Used reference software version as 2.5.3 as it was identified to be the earliest valid one for the 2+, and I believe it would apply all the same to the 2. If it's not the case though, I'll update later on!
