### ISSUE TITLE
Panel 4 Doesn't Seem to Work

### ISSUE THREAD

**Issue by efaden** [XaF/qolsysgw#13]
Should this work with the IQ Panel 4?  I assume it's pretty similar, but it can't seem to connect.  What's interesting is that even after enabling the integration the port doesn't seem to respond at all.

**Comment by XaF** [comment]
Hey there! I don't have an IQ Panel 4 and I've seen comments in the thread on the home assistant community forums saying that for the IQ Panel 4 the connection does not seem to work. I cannot really assist on that matter, but if you figure out a solution, please share it!

**Comment by XaF** [comment]
Oh pretty neat to know!!
Do you have all the functionalities working @cfsbhawkins ?

**Comment by cfsbhawkins** [comment]
> Oh pretty neat to know!! Do you have all the functionalities working @cfsbhawkins ?

I have not tried the arming/disarming stuff, but I can give it a test. I do get all the sensor/panel status information and that all seems to work.  What I am noticing thought and can send you logs is that after a while it will become unavailable. Only way I have found is to delete the MQTT topics and restart the integration then it all comes back.  Not sure if thats an issue with my setup or a known issue. Willing to help.

**Comment by murkumurdok** [comment]
> > Oh pretty neat to know!! Do you have all the functionalities working @cfsbhawkins ?
> 
> I have not tried the arming/disarming stuff, but I can give it a test. I do get all the sensor/panel status information and that all seems to work. What I am noticing thought and can send you logs is that after a while it will become unavailable. Only way I have found is to delete the MQTT topics and restart the integration then it all comes back. Not sure if thats an issue with my setup or a known issue. Willing to help.

Hi, I'm about to pull the trigger on an IQ panel 4 and I'm curious whether you're still experiencing the issues you described.

**Comment by XaF** [comment]
>  What I am noticing thought and can send you logs is that after a while it will become unavailable. Only way I have found is to delete the MQTT topics and restart the integration then it all comes back

Feels a bit weird that the MQTT topics need to be fully deleted. The only topics the integration are reading are not setup with persistence so shouldn't need to be removed. What do you see in the logs ? (if anything)
Is the integration losing connection with the panel and not reinitiating it ?

**Comment by cfsbhawkins** [comment]
I don't think it was an issue with the integration. I think it was with AppDaemon once I hardcoded a username/password for MQTT and stopped relying on it getting passed in by HA it started right up and has been working since.

**Comment by XaF** [comment]
Oh great! Thanks for the update, that's good to know! :)

**Comment by murkumurdok** [comment]
> I don't think it was an issue with the integration. I think it was with AppDaemon once I hardcoded a username/password for MQTT and stopped relying on it getting passed in by HA it started right up and has been working since.

Thank you both. Looking forward to trying this out
