### ISSUE TITLE
Special characters are not supported by home assistant mqtt.  The script should remove diacritics when used as an identifier

### ISSUE THREAD

**Issue by yepeekai** [XaF/qolsysgw#131]
### Before submitting this form

- [X] I have checked that there hasn't been a similar issue submitted in the past

- [X] I have updated the issue title to something relevant and clear to understand the bug I'm facing

### Description of the bug

In french, we use diacritics here and there on letters.  Ex: "porte patio salle à manger" or "chambre des maîtres".  I see in the log that qolsysgw is treating those entities but home assistant doesn't accept names containing special characters.

[this solution looks promising](https://stackoverflow.com/a/2633310/413464)

### Expected behavior

where spaces are replaced by underscore (identifier of some kind), the app should also remove diacritics ('à' should become 'a', 'î' should become 'i' etc.).  In this case : "porte patio salle à manger" would become "porte_patio_salle_a_manger"

### DEBUG logs

DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on homeassistant/binary_sensor/porte_patio_salle_à_manger/config (qos=0): b'{"name": "porte patio salle \\u00e0 manger", "device_class": "door", "state_topic": "homeassistant/binary_sensor/porte_patio_salle_\\u00e0_manger/state", "payload_on": "Open", "payload_off": "Closed", "availability_mode": "all", "availability": [{"topic": "homeassistant/alarm_control_panel/qolsys_panel/availability", "payload_available": "online", "payload_not_available": "offline"}, {"topic": "homeassistant/binary_sensor/porte_patio_salle_\\u00e0_manger/availability", "payload_available": "online", "payload_not_available": "offline"}, {"topic": "mqtt-client/status", "payload_available": "online", "payload_not_available": "offline"}], "json_attributes_topic": "homeassistant/binary_sensor/porte_patio_salle_\\u00e0_manger/attributes", "enabled_by_default": true, "unique_id": "qolsys_panel_s109_5754", "device": {"name": "Qolsys Panel", "identifiers": ["qolsys_panel"], "manufacturer": "Qolsys", "model": "IQ Panel 2+"}}'
WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/binary_sensor/porte_patio_salle_à_manger/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/integrations/mqtt/#discovery-topic

**Comment by XaF** [comment]
I don't think that `unidecode` can be used in `AppDaemon` unfortunately.
Might require something more direct such as removing all non-ascii characters!

**Comment by yepeekai** [comment]
In the same stackoverflow page, there’s a couple of answers using unicodedata.  Would that work?
