### ISSUE TITLE
Qolssys sending UTF-16 but qolsqw looking for UTF8 maybe?

### ISSUE THREAD

**Issue by continuousmining** [XaF/qolsysgw#163]
### Before submitting this form

- [X] I have checked that there hasn't been a similar issue submitted in the past

- [X] I have updated the issue title to something relevant and clear to understand the bug I'm facing

### Description of the bug

Should be able to decode the messages, but it seems IQ Panel 4 might be sending it in UTF-16.   MQTT Broker isn't seeing any of this.

### Expected behavior

Should see actual MQTT messages 

### DEBUG logs

2024-09-08 23:42:48.858152 INFO MQTT: Unable to decode MQTT message
2024-09-08 23:42:48.858522 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

2024-09-08 23:42:49.119569 INFO MQTT: Unable to decode MQTT message
2024-09-08 23:42:49.120493 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### Additional context

Issuing commands in the panel and getting these errors.  Looking to decipher the payloads.

**Comment by XaF** [comment]
According to the error message, these seem to be raised directly in the MQTT plugin of AppDaemon ?

**Comment by continuousmining** [comment]
AppDaemon

**Comment by Anto79-ops** [comment]
I posted the issue at AD just recently because I noticed this also in the AD logs.

https://github.com/hassio-addons/addon-appdaemon/issues/350

**Comment by Anto79-ops** [comment]
just curiious, has the new AD update to 0.16.7 solved this for you? I'm not seeing these in my logs anymore but i just updated 20 minutes ago so perhaps its to early to tell....

**Comment by Anto79-ops** [comment]
with the new AD, it has a better loging mechanism and now I can see what was causing this log. It was not Qolsys GW, it was some unreleated, but using MQTT.

What you can do is add a line to AD config.yaml to listen only to specific topics rather than everything on MQTT broker. So in my case, im only use AD for this integration so i added this to my adconfig.yaml file and no more logs:


```
      client_topics:
        - qolsys/#
```
like so:

```
apps:
  - app_class: MQTT
    app_name: mqtt
    config:
      broker: <your_mqtt_broker_url>
      port: <your_mqtt_broker_port>
      client_topics:
        - qolsys/#
```

this basically says AD should only listen to anything generated by qolsys
