### ISSUE TITLE
Heat/Freeze Sensor Types

### ISSUE THREAD

**Issue by cfsbhawkins** [XaF/qolsysgw#19]
Great work by the way! I saw you were looking for more sensors, these are part of the Smoke Detectors when you use a 345Mhz sensor on additional loops.

```
{'id': '5XXXX', 'type': 'Heat', 'name': 'Hallway Heat Sensor', 'group': 'smoke_heat', 'status': 'Closed', 'state': '0', 'zone_id': 12, 'zone_physical_type': 10, 'zone_alarm_type': 0, 'zone_type': 8, 'partition_id': 0}
 {'id': '5XXXX', 'type': 'Freeze', 'name': 'Hallway Freeze Sensor', 'group': 'freeze', 'status': 'Closed', 'state': '0', 'zone_id': 13, 'zone_physical_type': 6, 'zone_alarm_type': 0, 'zone_type': 17, 'partition_id': 0}
```

**Comment by XaF** [comment]
I guess these are coming from update messages ?
Do you have similar information from the initial INFO message when doing a sync ?

**Comment by cfsbhawkins** [comment]
Yes I will try and grab some more info from them, I was seeing them in the initial connection and sync.

**Comment by Anto79-ops** [comment]
Thanks for bringing this up. If you need another set of eyes I also have the sensors (qolsys heat/freeze 319.5). Just let me know, cheers

**Comment by XaF** [comment]
Hey @cfsbhawkins @Anto79-ops - I still need more data here if I am to add sensors for those.

Ideally, your initial `INFO` message from the panel for those sensors.
Also, any idea which matching type would make sense in Home Assistant ?

**Comment by Anto79-ops** [comment]
@XaF I was just thinking about this as I'm getting updates that you're updating the code.. How do I exactly get this information for you I can get it for you today if you tell me how to get it.

**Comment by XaF** [comment]
You need to have the `log_level: DEBUG` parameter in your `apps.yaml`, like so:

```json
qolsys_panel:
  module: gateway
  class: QolsysGateway
  log_level: DEBUG
  <rest_of_config>
```

And after that, you can check the AppDaemon logs while the panel is running.
You should be able to capture the `INFO` message, and ideally also a `ZONE_ACTIVE` and `ZONE_UPDATE` message (but I believe for those, the `ZONE_ACTIVE` is unlikely since it would mean they need to get triggered, but it seems it's going to be harder to do so for Heat/Freeze sensors!)

**Comment by Anto79-ops** [comment]
@XaF I think you're right because even my alarm.com account doesn't know what state the sensor is in it says it's unknown. They've never been triggered before.

I may have learned it in as a non-reporting sensor which could be part of the problem. However if you learn it in as an alarm sensor I then it does actually tell you this but it was a while ago when I did this

**Comment by XaF** [comment]
If you are able to provide the rest of the data, that could be useful still!

**Comment by Anto79-ops** [comment]
working on it now...please stand-by

**Comment by Anto79-ops** [comment]
I found this but I don't think its more useful than what the OP posted. If nothing new is shown below. What if I tamper the sensor with debug on?

`2022-12-20 14:44:14.430331 DEBUG qolsys_panel: Unknown sensor in Qolsys event: {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"6B11A3","type":"Freeze","name":"Mechanical Room High Tem","group":"freeze","status":"Closed","state":"0","zone_id":35,"zone_physical_type":6,"zone_alarm_type":0,"zone_type":17,"partition_id":0},"version":1,"requestID":"7a87f5dd-5076-4090-a5ad-689cd7bcd200"}`

and

`2022-12-20 14:44:13.257424 DEBUG qolsys_panel: Unknown sensor in Qolsys event: {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"6B11A2","type":"Freeze","name":"Mechanical Room Low Temp","group":"Freeze_Non_Reporting","status":"Closed","state":"0","zone_id":34,"zone_physical_type":6,"zone_alarm_type":3,"zone_type":17,"partition_id":0},"version":1,"requestID":"a3f5a4b3-6eb6-4bfc-8712-e252e795211f"}

`

**Comment by XaF** [comment]
The debug mode shows us any data the panel sends us. So if you temper we might get tempering information too, which sometimes shows the update message similar to the one we get when the sensor was triggered. Mind trying?

Worst case, I could try adding the sensor with the information we have, but might be missing some data 🤷‍♂️

**Comment by Anto79-ops** [comment]
ok, I'm going to try and capture a tamper AND heat alarm. I'm just going to try and use a blow dryer to activate it. Only needs to be 39oC to activate heat.

**Comment by XaF** [comment]
I opened the following issues for those sensors specifically:
- Heat #48 
- Freeze #49

**Comment by XaF** [comment]
Just merged #51 and about to merge #52 
This should be solving the addition of those sensors!

If you get the information that you were trying to get in your previous comment, please still forward it as it'll allow to verify that the behavior will be as expected in those situations :)

**Comment by Anto79-ops** [comment]
Thanks, I was able to trigger it and caught this information. By the way, the heat and freeze are different sensors BUT one sensor.


```
2022-12-20 17:00:37.375125 DEBUG qolsys_panel: Unknown sensor in Qolsys event: {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"6B11A3","type":"Freeze","name":"Mechanical Room High Tem","group":"freeze","status":"Open","state":"0","zone_id":35,"zone_physical_type":6,"zone_alarm_type":0,"zone_type":17,"partition_id":0},"version":1,"requestID":"4074a05c-7891-40b5-9969-4112db98c2ff"}

'new_value': 'DISARM'}
```



```
2022-12-20 17:00:37.366301 DEBUG qolsys_panel: Data received (len: 323): {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"6B11A3","type":"Freeze","name":"Mechanical Room High Tem","group":"freeze","status":"Open","state":"0","zone_id":35,"zone_physical_type":6,"zone_alarm_type":0,"zone_type":17,"partition_id":0},"version":1,"requestID":"4074a05c-7891-40b5-9969-4112db98c2ff"}
2022-12-20 17:00:37.371504 WARNING qolsys_panel: sensor of unknown type: {'id': '6B11A3', 'type': 'Freeze', 'name': 'Mechanical Room High Tem', 'group': 'freeze', 'status': 'Open', 'state': '0', 'zone_id': 35, 'zone_physical_type': 6, 'zone_alarm_type': 0, 'zone_type': 17, 'partition_id': 0}
2022-12-20 17:00:37.375125 DEBUG qolsys_panel: Unknown sensor in Qolsys event: {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"6B11A3","type":"Freeze","name":"Mechanical Room High Tem","group":"freeze","status":"Open","state":"0","zone_id":35,"zone_physical_type":6,"zone_alarm_type":0,"zone_type":17,"partition_id":0},"version":1,"requestID":"4074a05c-7891-40b5-9969-4112db98c2ff"}
```



`2022-12-20 17:00:37.366301 DEBUG qolsys_panel: Data received (len: 323): {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"6B11A3","type":"Freeze","name":"Mechanical Room High Tem","group":"freeze","status":"Open","state":"0","zone_id":35,"zone_physical_type":6,"zone_alarm_type":0,"zone_type":17,"partition_id":0},"version":1,"requestID":"4074a05c-7891-40b5-9969-4112db98c2ff"}`


`2022-12-20 17:00:37.375125 DEBUG qolsys_panel: Unknown sensor in Qolsys event: {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"6B11A3","type":"Freeze","name":"Mechanical Room High Tem","group":"freeze","status":"Open","state":"0","zone_id":35,"zone_physical_type":6,"zone_alarm_type":0,"zone_type":17,"partition_id":0},"version":1,"requestID":"4074a05c-7891-40b5-9969-4112db98c2ff"}`

**Comment by XaF** [comment]
Ok so it seems the changes I merged should be working for your sensors now! Thanks for the help!
Grab the last version and try it out! :)

**Comment by Anto79-ops** [comment]
Fantastic! Just updated and I see both my heat/freeze sensors now.

Turns out the heat was reporting so it triggered the alarm and a phone call from the monitoring station. My wife is not too happy about the siren and using her hair dryer :) lol

**Comment by XaF** [comment]
Oh woops! I remember using a panel option to put it in test mode in the past, which makes sure that alarm is not making any noise and not contacting the monitoring company either, as it's just a test mode, maybe worth enabling next time haha
