### ISSUE TITLE
Offline Door Sensor displays "Open" status in HA

### ISSUE THREAD

**Issue by cdrobey** [XaF/qolsysgw#20]
My door sensor went off-line and displays the sensor is open instead of unavailable.  The HA logbook displays open and starts automation.

**Comment by cdrobey** [comment]
Would you direct me to the logs files.  I was unable to find any issues in home-assistant.log as well as docker stdout details.

**Comment by nwf** [comment]
Sorry to necro a bug report, but is it really the case that the panel doesn't differentiate between "failed" and "unsafe" states for integration?  That's incredibly rude of it. :'(

**Comment by XaF** [comment]
The panel does have a distinction for those states, but through the 3rd party integration we receive the same message in both cases: "open".
There is no way to know if that "open" means that the sensor has been activated (e.g. Door open, motion detected) or if the sensor is unsafe (e.g. Tempered with, non-responsive).

**Comment by nwf** [comment]
Thanks.  That's... more reason to replace this inherited system with something else.  That said, thanks for all your hard work on `qolsysgw`; it was pretty smooth to get going (modulo finding my way around HA and friends) and it looks like it Just Works (TM) as best as the data stream it's given allows it.

**Comment by XaF** [comment]
So I played a bit with my sensors and tampered them, and seem to see some kind of pattern when a sensor is tampered with, where the message seem to be repeated. This is not instant, nor does it seem to be something that can work 100% of the time, but we might be able to get something working.
I _do not know_ if this is the same kind of information we would receive from an offline sensor, and it seems like if AppDaemon is restarted, when we pull the summary from the panel, we lose that information. I'll still try to see what kind of data we can get and if it makes sense to build that into `qolsysgw` even if it's partial information.

**Comment by XaF** [comment]
I put more details in #73 and merged #74 to add the support. I might also merge #75 to bubble up the tampered list to the partitions. These will thus be part of the next release.
