### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by PerfectBake420** [XaF/qolsysgw#21]
![Screenshot_20220329-163112_Home Assistant](https://user-images.githubusercontent.com/98441937/160701911-ed51a596-719a-46bc-9289-d22e00c56e7c.jpg)

**Comment by XaF** [comment]
Hey there, seems to be an issue with your installation in this case, not really an issue with `qolsysgw` !

**Comment by PerfectBake420** [comment]
This was working for approximately 4 months updating and everything and now
all of a sudden it won't update only this addon any further. You're telling
me it's not an issue with it reaching the URL? That's what the log says

**Comment by XaF** [comment]
Yes, but if you check your lock, it's not only complaining about this plugin but about another one too!
Also, the URL is github, and HACS handles the updates through github. This is thus not related to the code in this project, so not really possible to fix things for you from here :(

You can try removing the extension using HACS and adding it back. Maybe that'll fix the download and update!
