### ISSUE TITLE
No 3rd party integration option on my panel

### ISSUE THREAD

**Issue by ultimateguy** [XaF/qolsysgw#22]
When I go to Installation -> Devices -> Wi-Fi Devices, there is no option for 3rd party integration. Is there a way to add it? I have software version 2.6.2. I tried calling my security provider but they were clueless and said they had never heard of the 3rd party option before.

![image](https://user-images.githubusercontent.com/15295448/164591696-e771c32e-62d5-49a1-ac85-9005a0859272.png)

**Comment by XaF** [comment]
Seems to me you're simply using an admin code, but not the dealer nor installer code!

**Comment by ultimateguy** [comment]
This was the case - I was using the installer code, but apparently that's not good enough for 3rd party connections. Had to speak with 3 people at the security provider before I got someone who set the dealer code for me. (The defaults weren't working)

**Comment by XaF** [comment]
Ah, yes! I actually had the same problem where the installer code wasn't sufficient to configure the 3rd party integration. For some people, however, it is sufficient, not sure why !

If you check the "Requirements" section of the readme, I actually wrote it there too!

**Comment by ultimateguy** [comment]
Thanks! I'm new to the panel and didn't realize there were so many types of codes.
