### ISSUE TITLE
Bluetooth device state does not change

### ISSUE THREAD

**Issue by murkumurdok** [XaF/qolsysgw#23]
Hello, I paired my iPhone to the Qolsys panel with the hope of using it for some bluetooth presence detection, but the state of my iphone binary sensor is always shows up as "Away," regardless of whether my phone is connected to the panel via bluetooth or not.

**Comment by XaF** [comment]
Hello, are you able to see anything once all the logs enabled? If the panel is not sending any update, the integration won't be able to act on them.

**Comment by murkumurdok** [comment]
I don't see any log entries from just disabling and reeneabling bluetooth on the phone. I'll try later to see if the auto-disarm function while armed-away does naything

**Comment by murkumurdok** [comment]
> hi, just wanted to confirm this because I have bluetooth disarming enabled, and over the weekend, that happened a few times that our phones disarmed the panel via bluetooth. Upon checking the logs over the weekend, only "away/off" and the occassional "became unavialbe" is shown in the logs. Doesn't seem to show "home/on"?

Thank you for confirming this and saving me the effort.  I guess this issue can be closed unless anyone else has any other ideas?

**Comment by XaF** [comment]
Ok so if the debug logs don't contain any message from the panel to indicate when the bluetooth of the phone is detected, that's kind of expected we won't be able to get that information in Home Assistant either (as we depend on the panel's messages).
The integration uses the control4 interface, and it might very well be that control4 does not support nor care about those? (but then I'm not sure why we still send them as sensors, and just don't update them...)
