### ISSUE TITLE
New device types

### ISSUE THREAD

**Issue by cjones813** [XaF/qolsysgw#24]
Hello, Many thanks for this integration its fantastic. I have the following Unknown device types. Would be great if you could add those if possible. (I dont think the last 3 will be of much use)

### Auxiliary Pendant
```
2022-05-29 20:46:33.335795 WARNING qolsys_panel: sensor of unknown type: {'id': '101-6464', 'type': 'Auxiliary Pendant', 'name': 'Panic Alarm', 'group': 'fixedintrusion', 'status': 'Closed', 'state': '0', 'zone_id': 28, 'zone_physical_type': 11, 'zone_alarm_type': 0, 'zone_type': 21, 'partition_id': 0}
```

**This is just a standard door sensor that has an Auxiliary input I have a Panic Alarm wired into the input._** https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/mc-302e-pg2

### Siren
```
2022-05-29 20:46:33.340648 WARNING qolsys_panel: sensor of unknown type: {'id': '410-4121', 'type': 'Siren', 'name': 'Front Siren', 'group': 'Siren', 'status': 'Closed', 'state': '0', 'zone_id': 29, 'zone_physical_type': 1, 'zone_alarm_type': 3, 'zone_type': 14, 'partition_id': 0}
```

**Standard outdoor Siren** https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/sr-740-pg2

### Keypad
```
2022-05-29 20:46:33.349919 WARNING qolsys_panel: sensor of unknown type: {'id': '374-5234', 'type': 'Keypad', 'name': 'Upstairs Keypad', 'group': 'fixedintrusion', 'status': 'Closed', 'state': '0', 'zone_id': 31, 'zone_physical_type': 4, 'zone_alarm_type': 0, 'zone_type': 104, 'partition_id': 0}
```

**Keypad** https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/kp-160-pg2

### KeyFob
```
2022-05-29 20:46:33.354810 WARNING qolsys_panel: sensor of unknown type: {'id': '301-2914', 'type': 'KeyFob', 'name': "Keyfob 1", 'group': 'mobileintrusion', 'status': 'Closed', 'state': '0', 'zone_id': 32, 'zone_physical_type': 3, 'zone_alarm_type': 0, 'zone_type': 102, 'partition_id': 0}
```

**Keyfob** https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/kf-235-pg2

Many thanks!!

**Comment by XaF** [comment]
Would you be able to provide the INFO message for those too ?
As well as any status update you can observe when acting with them ?

Thanks!

**Comment by cjones813** [comment]
Yes no problem. This may be a stupid question but where do I find this info message? Thank you!

**Comment by XaF** [comment]
So you'll need to enable debug mode to see everything and not just warnings, and you should see all the interactions with your panel in the appdaemon logs. From there you should see that when the integration connects to your panel it sends an INFO request and receives a bunch of data with the panel partition and all the sensors. It's a slightly different message than a zone update, so I want to know what it contains! :)

**Comment by Pablo1** [comment]
@XaF - I also have multiple sensors that are not being recognized. I'm not sure if you're still actively developing the integration but I would be happy to either submit a pull request or provide you with the info you need to add the sensor types.

**Comment by XaF** [comment]
Hello @Pablo1 - I am indeed still maintaining this integration. I have been working - for a bit - on writing tests for it, since I wanna make sure that adding new features or options does not break existing features of it (and adding new features also makes it more complicated to do comprehensive testing without actual tests).

That being said, if you have information for sensors, I'll happily take this information, and any suggestion about what should be their representation in Home Assistant. I, of course, can only support things that are natively supported by the Control4 interface of the panel! Thanks!

**Comment by Pablo1** [comment]
The three sensor types that I've noticed are missing are

Auxiliary Pendant
Key Fob
Keypad

Not sure what they should map to. I use auxiliary pendant for a custom trouble sensor (just a door sensor). Keypad is an IQ Remote Keypad.

If you point me to the right spot in the code I can make sure to add some debugging and capture the exact json for you.

**Comment by XaF** [comment]
With debug enabled for the AppDaemon app, you should already have the right debugging enabled. You should be able to see in the logs (of AppDaemon) any message that is being ignored by `qolsysgw`. It would be good to know what are the Control4 messages that the panel sends for those elements, as to identify if it makes sense to map them in Home Assistant, and what to map them to, and what actions would be reported to Home Assistant for those!

**Comment by Pablo1** [comment]
Here you go:

appdaemon.log.1:2022-11-09 22:45:29.916219 DEBUG qolsys_panel: Unknown
sensor in Qolsys event:
{"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"101-5037","type":"Auxiliary
Pendant","name":"Combustible Gas
Trouble","group":"fixedmedical","status":"Closed","state":"0","zone_id":38,"zone_physical_type":1,"zone_alarm_type":0,"zone_type":21,"partition_id":0},"version":1,"requestID":"89662c50-95c0-442a-b9df-22de9b9e8073"}


appdaemon.log.1:2022-11-09 22:45:55.972517 DEBUG qolsys_panel: Unknown
sensor in Qolsys event:
{"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"305-7957","type":"KeyFob","name":"Key
Fob","group":"mobileintrusion","status":"Closed","state":"0","zone_id":13,"zone_physical_type":3,"zone_alarm_type":0,"zone_type":102,"partition_id":0},"version":1,"requestID":"bfff9e96-43ce-430d-9dd8-a9d3a245c860"}

**Comment by XaF** [comment]
Are you able to see other messages for those with different status, corresponding to when you press the button, or a delay?

Are you able to share your `ZONE_INFO` message too, which should contain those two?

Thanks!

**Comment by Pablo1** [comment]
I assume you mean "INFO"? If so here they are:

`{"id":"305-7957","type":"KeyFob","name":"Key Fob","group":"mobileintrusion","status":"Closed","state":"0","zone_id":13,"zone_physical_type":3,"zone_alarm_type":0,"zone_type":102,"partition_id":0}`

`{"id":"101-5037","type":"Auxiliary Pendant","name":"Combustible Gas Trouble","group":"fixedmedical","status":"Closed","state":"0","zone_id":38,"zone_physical_type":1,"zone_alarm_type":0,"zone_type":21,"partition_id":0}`

There's also a remote keypad which often shows up as Unknown as well:

`{"id":"IQR1","type":"Keypad","name":"IQ Remote 1","group":"fixedintrusion","status":"Closed","state":"0","zone_id":48,"zone_physical_type":4,"zone_alarm_type":0,"zone_type":104,"partition_id":0}`

**Comment by XaF** [comment]
Does the keypad have any updates when you use it?

**Comment by Pablo1** [comment]
Unfortunately it does not appear to have any updates. Even if I arm/disarm from the IQ Remote Keypad it doesn't seem to make a distinction between the IQ Remote and the main keypad.

**Comment by XaF** [comment]
Yeah ok, I believe it's just indicating that the keypad exists but there's no real interest in having it appear in Home Assistant then! I might just end up ignoring it but actively (so it won't show messages about "unknown" sensor in the logs)

**Comment by Pablo1** [comment]
That seems reasonable. Thank you so much for creating this integration. The previous one had some pretty serious bugs that I created a PR for but it never got merged. Please let me know if I can help.

**Comment by XaF** [comment]
I'm holding on new features and additions until I have enough testing of the integration, as I want to make sure anything new that end up being added does not break what currently works. So that might take a little bit still, but it's on the way! (I'm currently working on that in a side-branch [that you can see there](https://github.com/XaF/qolsysgw/tree/xaf/add_tests))

**Comment by Pablo1** [comment]
Thank you. Your hard work is definitely appreciated. Being able to use all of the Qolsys sensors as part of HA is awesome !

**Comment by XaF** [comment]
Created issues for each new sensor type, so I can aggregate all the information I need for each in specific places:
- Keypad in #50 
- Keyfob in #45 
- Siren in #47 
- Auxiliary Pendant in #46 

Going to close this issue as I grabbed all the information I needed that was available here!
