### ISSUE TITLE
Add support for `Keypad` sensor type

### ISSUE THREAD

**Issue by XaF** [XaF/qolsysgw#50]
## Sensor information

- **type:** `Keypad`
- **[Home Assistant device class](https://www.home-assistant.io/integrations/binary_sensor/#device-class):** TBD!!!
- **Panel sends sensor status updates?**
  - [ ] Yes, I can see the Open/Close messages (I have been able to capture `ZONE_ACTIVE` messages)
  - [ ] No, it seems to only tell us the sensor exists, but never update its state

## Decision

**Will add / Won't add ?** TBD

### `ZONE_INFO`

```json
{
  "id": "374-5234",
  "type": "Keypad",
  "name": "Upstairs Keypad",
  "group": "fixedintrusion",
  "status": "Closed",
  "state": "0",
  "zone_id": 31,
  "zone_physical_type": 4,
  "zone_alarm_type": 0,
  "zone_type": 104,
  "partition_id": 0
}
```

```json
{
  "id": "IQR1",
  "type": "Keypad",
  "name": "IQ Remote 1",
  "group": "fixedintrusion",
  "status": "Closed",
  "state": "0",
  "zone_id": 48,
  "zone_physical_type": 4,
  "zone_alarm_type": 0,
  "zone_type": 104,
  "partition_id": 0
}
```

### `ZONE_UPDATE`

```json
N/A
```

### `ZONE_ACTIVE`

```json
N/A
```

**Comment by halfordfan** [comment]
I doubt I can help with the code, but I'm a willing tester.  My panel is set up on a test bench for the next few weeks.
