### ISSUE TITLE
Cant find apps.yaml

### ISSUE THREAD

**Issue by PerfectBake420** [XaF/qolsysgw#7]
I have HA 2021.12.10 running in a vm on ubuntu 20.04. It is up and running. I have installed hacs and downloaded the qolsysgw addon. When i make it to the step that says i need to edit the apps.yaml file, I can not find it. When I go into /config/appdaemon/apps there is a qolsysqw directory. There is no apps.yaml in either the apps directory or the qolsysgw directory. 
Can anyone give me advice on how to continue?

**Comment by XaF** [comment]
If the file does not exist, you can create it and put the configuration for `qolsysgw` directly in there

**Comment by PerfectBake420** [comment]
> If the file does not exist, you can create it and put the configuration for `qolsysgw` directly in there

I am still a noob to Home Assistant but I am a technical person.  I just want clarification.  Are you telling me I just need to create the file apps.yaml and put the config info into it? Are you telling me to copy a file from the qolsysgw directory into the apps directory? I noticed the file is not in the code from here also. So if it is normal to not have the file, where is the documentation to get you configured correctly? Thank you for your response.

**Comment by XaF** [comment]
Yes, if the file does not exist, just create it in the `apps` directory, next to the `qolsysgw` directory.
And the documentation about what to put in that `apps.yaml` file is [in the README](https://github.com/XaF/qolsysgw#required-configuration) in the "required configuration" subsection of the section about how to configure `qolsysgw` !
