### ISSUE TITLE
Add support for `tilt` sensor type

### ISSUE THREAD

**Issue by CitizenRacer** [XaF/qolsysgw#77]
### Before submitting this form

- [X] I have checked that this sensor type was not suggested for addition before; I know that it could
be in open or closed issues, and if there was another issue mentioning this sensor type I could
simply comment in it instead

- [X] I have updated the `<sensor type>` mention in the title of the issue, but left the issue title
as it was otherwise

- [X] I understand that if I want to suggest the addition of more than a single sensor type, I need
to file that form for each separate type

### Sensor type

`Tilt`

### Home Assistant device class

`garage_door`

### Does the panel send sensor status updates?

- [x] Yes, I can see the Open/Close messages (I have been able to capture `ZONE_ACTIVE` messages)
- [ ] No, it seems to only tell us the sensor exists, but never update its state

### Sensor data from an `INFO` message

I don't have an Info message all I have is:

 from the MQTT Qolsys error message.
From "homeassistant/sensor/qolsys_panel_last_error/attributes"
QoS: 0
Payload:

type: UnknownQolsysSensorException
desc: >-

```json
{
  "id": "7389AB",
  "type": "Tilt",
  "name": "Garage Tilt",
  "group": "garageTilt1",
  "status": "Closed",
  "state": "0",
  "zone_id": 8,
  "zone_physical_type": 1,
  "zone_alarm_type": 3,
  "zone_type": 16,
  "partition_id": 0
}
```

### Sensor data from a `ZONE_EVENT`'s `ZONE_UPDATE` message

I don't have a ZONE_EVENT  all I have is:

 from the MQTT Qolsys error message.
From "homeassistant/sensor/qolsys_panel_last_error/attributes"
QoS: 0
Payload:

type: UnknownQolsysSensorException
desc: >-

```json
{
  "id": "7389AB",
  "type": "Tilt",
  "name": "Garage Tilt",
  "group": "garageTilt1",
  "status": "Closed",
  "state": "0",
  "zone_id": 8,
  "zone_physical_type": 1,
  "zone_alarm_type": 3,
  "zone_type": 16,
  "partition_id": 0
}
```

### Sensor data from a `ZONE_EVENT`'s `ZONE_ACTIVE` message

I don't have an Info message all I have is:

 from the MQTT Qolsys error message.
From "homeassistant/sensor/qolsys_panel_last_error/attributes"
QoS: 0
Payload:

type: UnknownQolsysSensorException
desc: >-

```json
{
  "id": "7389AB",
  "type": "Tilt",
  "name": "Garage Tilt",
  "group": "garageTilt1",
  "status": "Closed",
  "state": "0",
  "zone_id": 8,
  "zone_physical_type": 1,
  "zone_alarm_type": 3,
  "zone_type": 16,
  "partition_id": 0
}
```
![Screenshot 2023-01-15 at 9 06 46 PM](https://user-images.githubusercontent.com/14790049/212602785-947c947a-10a1-4f4c-a30b-fcb3e96a15d7.jpg)

### Additional context

The sensor doesn't show up under my alarm device or in the list of entities, but it is triggering the qolys error sensor.

**Comment by XaF** [comment]
Hello! If you change the status of your sensor by triggering it (so it would be open), are you seeing an update to the error description (with `status` to `Open` instead of `Closed` as in the data you provided)?

Also, as described when submitting the issue, if you have the debug logs enabled and you look at the logs of AppDaemon, you should be able to see the content of the `INFO` `SUMMARY` message and any `ZONE_ACTIVE`. The later should also tell us if the sensor changes state when you trigger it.

**Comment by CitizenRacer** [comment]
Yes, it moves from open to close and vice versa:

I'll try to get the logs next, I couldn't see them in the AppDaemon logs before.

````json
{
  "id": "7389AB",
  "type": "Tilt",
  "name": "Garage Tilt",
  "group": "garageTilt1",
  "status": "Open",
  "state": "0",
  "zone_id": 8,
  "zone_physical_type": 1,
  "zone_alarm_type": 3,
  "zone_type": 16,
  "partition_id": 0
}

{
  "id": "7389AB",
  "type": "Tilt",
  "name": "Garage Tilt",
  "group": "garageTilt1",
  "status": "Closed",
  "state": "0",
  "zone_id": 8,
  "zone_physical_type": 1,
  "zone_alarm_type": 3,
  "zone_type": 16,
  "partition_id": 0
}

**Comment by XaF** [comment]
It is indeed! And it confirms that your tilt sensor does change state to Open, so can be fully (and usefully) integrated! Thanks!

**Comment by CitizenRacer** [comment]
Thank you for being so awesome. I didn't see a "buy me a coffee" link, do you have one? I'd love to buy you a coffee or beer.
